name: .Net Publish Package

on:
  create:
    branches:
      - release/**

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'src/Codescovery.Library.Commons.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Build Version
      run: |
        Write-Host $Env:GITHUB_REF
        $version =  $Env:GITHUB_REF.replace('refs/heads/release/','')
        echo "BUILD_VERSION=$version"
        Write-Host $Env:BUILD_VERSION
      shell: pwsh
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=$Env:BUILD_VERSION --no-restore

    - name: Run tests
      run: dotnet test /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal
      
    - name: Publish
      if: startsWith(github.ref, 'refs/heads/release')
      run: nuget push **\*.nupkg -Source 'https://nuget.pkg.github.com/NAMESPACE/index.json' -ApiKey ${{secrets.NUGET_API_KEY_GITHUB}}
