name: .Net Publish Package

on:
  create:
    branches:
      - release/**

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION_PATH: 'src/Codescovery.Library.Commons.sln'
      PACKAGE_PROJECT_PATH: 'src/Package/Codescovery.Library.Commons/Codescovery.Library.Commons.csproj'
      TEST_PROJECT_PATH: 'src/Tests/Codescovery.Library.Commons.Test/Codescovery.Library.Commons.Test.csproj'
      NUGET_SOURCE: 'https://nuget.pkg.github.com/NAMESPACE/index.json'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get Build Version
      run: |
        Write-Host $Env:GITHUB_REF
        $version =  $Env:GITHUB_REF.replace('refs/heads/release/','')
        echo "BUILD_VERSION=$version" >> $Env:GITHUB_ENV
        Write-Host $Env:BUILD_VERSION
      shell: pwsh

    - name: Restore dependencies
      run: dotnet restore ${{env.SOLUTION_PATH}}

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x

    - name: Build
      run: dotnet build ${{env.PACKAGE_PROJECT_PATH}} --configuration ${{env.BUILD_CONFIG}} -p:Version=${{env.BUILD_VERSION}} --no-restore
      
    - name: Pack
      run: dotnet pack ${{env.PACKAGE_PROJECT_PATH}} --configuration ${{env.BUILD_CONFIG}} --no-build --no-restore -o ${{env.DOTNET_ROOT}}/artifact /p:Version
      
    - name: List build output
      run: |
        cd $Env:DOTNET_ROOT
        cd ./artifact
        ls
      shell: pwsh
      
    - name: Run tests
      run: dotnet test ${{env.TEST_PROJECT_PATH}} /p:Configuration=${{env.BUILD_CONFIG}} --no-restore --verbosity normal
      
    - name: Publish
      if: startsWith(github.ref, 'refs/heads/release')
      run: dotnet nuget push ${{env.DOTNET_ROOT}}/artifact/*.nupkg --source ${{env.NUGET_SOURCE}} --api-key ${{secrets.NUGET_API_KEY_GITHUB}}
